services:
  - type: web
    name: flask-tareas-rene
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
